server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/drug?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTime=UTC
    username: root
    password: zx258013zx
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    static-path-pattern: /static/**   #加载静态资源的路径
  thymeleaf:
    prefix: classpath:/templates      #classpath:表示resoutces文件夹
    cache: false

